import type { NextConfig } from "next";

// The CSP only sets directives that can't block the site's own scripts,
// styles, fonts or media (YouTube embeds, WebGL textures, inline JSON-LD):
// it stops clickjacking, plugin injection and <base>/form hijacking.
const securityHeaders = [
  {
    key: "Content-Security-Policy",
    value: "frame-ancestors 'none'; object-src 'none'; base-uri 'self'; form-action 'self'",
  },
  { key: "X-Frame-Options", value: "DENY" },
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  {
    key: "Permissions-Policy",
    value: "camera=(), microphone=(), geolocation=(), payment=(), usb=()",
  },
  {
    key: "Strict-Transport-Security",
    value: "max-age=63072000; includeSubDomains",
  },
];

const nextConfig: NextConfig = {
  poweredByHeader: false,
  // Keep the existing knowledge sources available to the Node chat route when
  // deploying with output file tracing. No folder is generated by this setting.
  outputFileTracingIncludes: {
    "/api/chat": ["./knowledge/**/*"],
    // Served by /resume.pdf until a resume is uploaded from /admin
    "/resume.pdf": ["./assets/resume.pdf"],
  },
  // Bundled into the /admin server actions, the undici fetch that @vercel/blob
  // uploads with comes out undefined ("a is not a function"); load it from
  // node_modules instead
  serverExternalPackages: ["@vercel/blob"],
  experimental: {
    // Resume uploads from /admin (the 1 MB default is too small for a PDF)
    serverActions: { bodySizeLimit: "5mb" },
  },
  async headers() {
    return [{ source: "/:path*", headers: securityHeaders }];
  },
  async redirects() {
    return [
      // The site moved to its own domain; the production *.vercel.app alias
      // would otherwise serve a duplicate copy that competes in search.
      {
        source: "/:path*",
        has: [{ type: "host", value: "rajdeepkotoky.vercel.app" }],
        destination: "https://www.rajdeepkotoky.com/:path*",
        permanent: true,
      },
      // /casestudies duplicated /projects; the ?project= query is kept.
      { source: "/casestudies", destination: "/projects", permanent: true },
    ];
  },
};

export default nextConfig;
