import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Keep the existing knowledge sources available to the Node chat route when
  // deploying with output file tracing. No folder is generated by this setting.
  outputFileTracingIncludes: {
    "/api/chat": ["./knowledge/**/*"],
  },
};

export default nextConfig;
